#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase 1> /dev/null
rm -rf *.txt
rm -rf *.coco


#------------------------------------------------------------------------------
