#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
ml OpenFOAM/4.1
source $FOAM_BASH
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


cleanCase 1> /dev/null

#------------------------------------------------------------------------------
