#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
rm -f *.txt
cleanCase 1> /dev/null
find -type d | grep -P '0\.0+0$' | xargs rm -rf {};
rm -f *.coco

#------------------------------------------------------------------------------
