#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
ml OpenFOAM/4.1
source $FOAM_BASH
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

runApplication blockMesh 1> /dev/null


#------------------------------------------------------------------------------
