site_name: CoCoNuT
repo_url: https://github.com/pyfsi/coconut
edit_uri: ''
site_url: ''
site_description: site_description
use_directory_urls: false
theme:
    name: 'material'
    logo: 'images/logo.png'
    feature:
        tabs: true
    favicon: 'assets/images/favicon.ico'
    palette:
        primary: 'green'
        accent: 'green'
markdown_extensions:
    - codehilite
    - pymdownx.arithmatex
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
nav:
  - Introduction:
      - CoCoNuT: README.md
  - Coupling components:
      - General: coupling_components.md
      - convergence_criteria.md
      - Coupled solvers:
          - coupled_solvers.md
          - models.md
      - mappers.md
      - predictors.md
      - Solver wrappers:
          - General: solver_wrappers.md
          - abaqus.md
          - fluent.md
          - kratos.md
          - openfoam.md
          - python.md
  - Data structure:
      - data_structure.md
  - Documentation:
      - docs.md
  - Examples:
      - General: examples.md
      - Tube:
          - Python TubeFlow - Python TubeStructre: tube_tube_flow_tube_structure.md
          - Python TubeFlow - Python TubeRingmodel: tube_tube_flow_tube_ringmodel.md
          - Python TubeFlow - Abaqus 2D: tube_tube_flow_abaqus2d.md
          - Fluent 2D - Python TubeStructure: tube_fluent2d_tube_structure.md
          - Fluent 2D - Abaqus 2D: tube_fluent2d_abaqus2d.md
          - Fluent 2D - Abaqus 2D - Steady: tube_fluent2d_abaqus2d_steady.md
          - Fluent 3D - Abaqus 2D: tube_fluent3d_abaqus2d.md
          - Fluent 3D - Abaqus 3D: tube_fluent3d_abaqus3d.md
          - Fluent 3D - Kratos Structure 3D: tube_fluent3d_kratos_structure3d.md
          - OpenFOAM 3D - Abaqus 3D: tube_openfoam3d_abaqus3d.md
          - OpenFOAM 3D - Kratos Structure 3D: tube_openfoam3d_kratos_structure3d.md
      - Turek benchmark:
          - Fluent 2D - Abaqus 2D: turek_fluent2d_abaqus2d.md
          - Fluent 2D - Abaqus 2D - Steady: turek_fluent2d_abaqus2d_steady.md
      - Test single solver: test_single_solver.md
  - Tests:
      - tests.md
